In [1]:
from nn import Tensor
import numpy as np

In [2]:
a = Tensor([1, 2, 3, 4, 5], autograd=True)
b = Tensor([1, 1, 1, 1, 1], autograd=True)
c = Tensor([5, 4, 3, 2, 1], autograd=True)

In [3]:
d = a + b
e = b + c
f = d + e

In [4]:
f.backward(Tensor(np.array([1,1,1,1,1])))

In [5]:
b.grad

array([2, 2, 2, 2, 2])

In [6]:
a.grad

array([1, 1, 1, 1, 1])

In [7]:
f.grad

array([1, 1, 1, 1, 1])

In [8]:
e.grad

array([1, 1, 1, 1, 1])

In [9]:
d.grad

array([1, 1, 1, 1, 1])

In [10]:
c.grad

array([1, 1, 1, 1, 1])