In [2]:
from nn import Tensor
import numpy as np

In [2]:
a = Tensor([1, 2, 3, 4, 5], autograd=True)
b = Tensor([1, 1, 1, 1, 1], autograd=True)
c = Tensor([5, 4, 3, 2, 1], autograd=True)

In [3]:
d = a + (-b)
e = -b + c
f = d + e

In [4]:
f.backward(Tensor(np.array([1,1,1,1,1])))

In [5]:
b.grad

array([-2, -2, -2, -2, -2])

In [6]:
a.grad

array([1, 1, 1, 1, 1])

In [7]:
f.grad

array([1, 1, 1, 1, 1])

In [8]:
e.grad

array([1, 1, 1, 1, 1])

In [9]:
d.grad

array([1, 1, 1, 1, 1])

In [10]:
c.grad

array([1, 1, 1, 1, 1])

In [11]:
x = np.array([[1,2,3], [4,5,6]])

In [24]:
x.expand(1, 4)

AttributeError: 'numpy.ndarray' object has no attribute 'expand'

In [25]:
a = list(range(0, 3))

In [26]:
a

[0, 1, 2]

In [34]:
a.insert(2, 5)

In [35]:
a

[0, 1, 5, 3, 3, 2, 3]

In [36]:
np.random.seed(0)

In [37]:
data = np.array([[0,0],[0,1],[1,0],[1,1]]) 
target = np.array([[0],[1],[0],[1]])

In [38]:
weights_0_1 = np.random.rand(2,3) 
weights_1_2 = np.random.rand(3,1)

In [54]:
for i in range(10):
    layer_1 = data.dot(weights_0_1)
    layer_2 = layer_1.dot(weights_1_2)
    
    diff = layer_2 - target
    sqdiff = diff * diff
    
    loss = sqdiff.sum(0)
    layer_1_grad = diff.dot(weights_1_2.transpose())
    weight_1_2_update = layer_1.transpose().dot(diff)
    weight_0_1_update = data.transpose().dot(layer_1_grad)
    weights_1_2 -= weight_1_2_update * 0.1 
    weights_0_1 -= weight_0_1_update * 0.1 
    print(loss[0])
    

4.383578836980046e-18
3.2634215622732162e-18
2.4295035861860575e-18
1.808680472846636e-18
1.3464996266768828e-18
1.0024220121533903e-18
7.462681837062828e-19
5.555706212631068e-19
4.1360303224077595e-19
3.0791299967506016e-19


In [1]:
from optimizers import SGD
from nn import Tensor, Linear, Sequential
import numpy as np

data = Tensor(np.array([[0,0],[0,1],[1,0],[1,1]]), autograd=True) 
target = Tensor(np.array([[0],[1],[0],[1]]), autograd=True)

model = Sequential([Linear(2,3), Linear(3,1)])

optim = SGD(parameters=model.get_parameters(), lr=0.05)

for i in range(10):
    pred = model.forward(data)
    loss = ((pred - target)*(pred - target)).sum(0) 
    loss.backward(Tensor(np.ones_like(loss.data)))
    optim.step()
    print(loss)

[1.99563159]
[1.32866097]
[1.07086095]
[0.94970258]
[0.85893807]
[0.75953174]
[0.64672724]
[0.51628995]
[0.32363307]
[0.0919175]
